(() => {
  const TOTAL=48000, stage=document.getElementById('stage'), a=document.getElementById('characterA'), b=document.getElementById('characterB'), label=document.getElementById('sceneLabel'), type=document.getElementById('sceneType'), name=document.getElementById('sceneName'), intro=document.getElementById('introCard'), hearts=document.getElementById('hearts'), sparkles=document.getElementById('sparkles'), progress=document.getElementById('progressBar'), replay=document.getElementById('replay');
  const ASSETS={idle:'./assets/idle.webp',smile:'./assets/smile.webp',wink:'./assets/wink.webp',serious:'./assets/serious.webp',charm:'./assets/charm.webp',wave:'./assets/wave.webp',heart:'./assets/heart.webp',dance:'./assets/dance.webp',kiss:'./assets/kiss.webp'};
  Object.values(ASSETS).forEach(src=>{const img=new Image();img.src=src});
  let front=a,back=b,timers=[],raf=0,startAt=0,heartTimer=null,sparkTimer=null,runId=0;
  const later=(ms,fn)=>{const id=setTimeout(fn,ms);timers.push(id);return id};
  function clearRun(){timers.forEach(clearTimeout);timers=[];clearInterval(heartTimer);clearInterval(sparkTimer);heartTimer=sparkTimer=null;cancelAnimationFrame(raf);stage.className='stage';label.classList.remove('show');intro.classList.remove('show');hearts.innerHTML='';sparkles.innerHTML=''}
  function labelScene(kind,title){type.textContent=kind;name.textContent=title;label.classList.remove('show');requestAnimationFrame(()=>requestAnimationFrame(()=>label.classList.add('show')))}
  function setMode(mode=''){[...stage.classList].filter(c=>c.startsWith('mode-')).forEach(c=>stage.classList.remove(c));if(mode)stage.classList.add(`mode-${mode}`)}
  function flash(){stage.classList.remove('flash');void stage.offsetWidth;stage.classList.add('flash');later(520,()=>stage.classList.remove('flash'))}
  function swap(asset,shot='full'){back.src=ASSETS[asset];back.className=`character ${back===a?'character-a':'character-b'} ${shot==='close'?'close-shot':'full-shot'}`;back.getBoundingClientRect();back.classList.add('is-visible');front.classList.remove('is-visible');const old=front;front=back;back=old}
  function makeHeart(big=false){const h=document.createElement('span');h.className='heart';h.textContent='♥';h.style.left=`${38+Math.random()*27}%`;h.style.top=`${38+Math.random()*25}%`;h.style.setProperty('--x',`${-80+Math.random()*160}px`);h.style.setProperty('--y',`${-120-Math.random()*170}px`);h.style.setProperty('--r',`${-24+Math.random()*48}deg`);if(big)h.style.fontSize='clamp(28px,6vh,62px)';hearts.appendChild(h);later(1800,()=>h.remove())}
  function makeSpark(){const s=document.createElement('i');s.className='spark';s.style.left=`${24+Math.random()*52}%`;s.style.top=`${24+Math.random()*54}%`;s.style.setProperty('--sx',`${-35+Math.random()*70}px`);s.style.setProperty('--sy',`${-45+Math.random()*60}px`);sparkles.appendChild(s);later(1200,()=>s.remove())}
  function startHearts(rate=420){clearInterval(heartTimer);makeHeart(true);heartTimer=setInterval(()=>makeHeart(Math.random()>.72),rate)} function stopHearts(){clearInterval(heartTimer);heartTimer=null}
  function startSparks(rate=260){clearInterval(sparkTimer);sparkTimer=setInterval(makeSpark,rate)} function stopSparks(){clearInterval(sparkTimer);sparkTimer=null}
  const scenes=[[0,()=>{swap('idle','full');intro.classList.add('show');label.classList.remove('show')}],[2400,()=>{intro.classList.remove('show');swap('smile','close');labelScene('EXPRESSION','SMILE');flash()}],[5400,()=>{swap('wink','close');labelScene('EXPRESSION','WINK');flash()}],[8400,()=>{swap('serious','close');labelScene('EXPRESSION','SERIOUS')}],[11400,()=>{swap('charm','close');labelScene('EXPRESSION','CHARM');startSparks(330)}],[14400,()=>{stopSparks();setMode('wave');swap('wave','full');labelScene('MOTION','BYE-BYE');flash()}],[20200,()=>{setMode('heart');swap('heart','full');labelScene('MOTION','HEART');startHearts(520)}],[26200,()=>{stopHearts();setMode('dance');swap('dance','full');labelScene('MOTION','DANCE');startSparks(180);flash()}],[36800,()=>{stopSparks();setMode('kiss');swap('kiss','full');labelScene('MOTION','KISS');startHearts(330);flash()}],[42300,()=>{stopHearts();setMode('wave');swap('wave','full');labelScene('FINALE','SEE YOU');startSparks(250)}],[46800,()=>{stopSparks();label.classList.remove('show');stage.classList.add('fadeout')}]];
  function play(){clearRun();runId++;const myRun=runId;front=a;back=b;a.className='character character-a is-visible full-shot';b.className='character character-b full-shot';a.src=ASSETS.idle;b.removeAttribute('src');progress.style.width='0%';scenes.forEach(([ms,fn])=>later(ms,()=>{if(runId===myRun)fn()}));startAt=performance.now();const tick=now=>{if(runId!==myRun)return;const elapsed=now-startAt;progress.style.width=`${Math.min(100,elapsed/TOTAL*100)}%`;if(elapsed<TOTAL)raf=requestAnimationFrame(tick);else if(new URLSearchParams(location.search).get('once')!=='1')later(1200,play)};raf=requestAnimationFrame(tick)}
  replay.addEventListener('click',play);window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();play()}});window.addEventListener('load',()=>later(250,play));
})();
